### PR TITLE
Popup window

### PR DESCRIPTION
**Pull request by ppmarq1**
Hi! We kindly ask you for a review of this. We've completed this milestone where we were required to:

When the user clicks (or taps) the button to check project details, the popup with details about the project appears.
When the user clicks (or taps) the close (X) button, the popup disappears.
You should implement popups for both mobile and desktop screen sizes:
Mobile popup and Desktop popup

For each project it must be stored the following pieces of data in a JavaScript object, at a minimum: name, description, featured image, technologies, link to live version, link to source.
The main pages is updated automatically, so that the projects section is created dynamically using the information stored in that JavaScript object. 

Best Regards,

Pedro Marques

### CODE REVIEW

**Comment by ppmarq1** [comment]
Due to technical problems with the computer of my code partner, she was not able to push the changes that she contributed. So, I was push all code from myself.

**Comment by MeqdamAlqudah** [comment]
> Due to technical problems with the computer of my code partner, she was not able to push the changes that she contributed. So, I was push all code from myself.

okay bro I will consider this

**Comment by ppmarq1** [comment]
Thank you!

Em sáb., 16 de abr. de 2022 20:59, Meqdam Qudah ***@***.***>
escreveu:

**Review by MeqdamAlqudah — APPROVED** [review]
Hi @ppmarq1 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
